# Generated by Django 3.0.2 on 2020-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseador',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
