# Generated by Django 3.0.2 on 2020-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='pash',
            field=models.ManyToManyField(blank=True, to='tablas.Paseador'),
        ),
    ]
